"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import TYPE_CHECKING, Any

from bs4 import BeautifulSoup
from bs4._typing import (
    _Encoding,
    _Encodings,
    _InvertedNamespaceMapping,
    _NamespaceMapping,
    _RawMarkup,
)
from bs4.builder import (
    HTMLTreeBuilder,
    TreeBuilder,
)
from bs4.element import (
    ProcessingInstruction,
)
from lxml import etree

__license__ = ...
__all__ = ["LXMLTreeBuilder", "LXMLTreeBuilderForXML"]
if TYPE_CHECKING: ...
LXML: str = ...
type _LXMLParser = etree.XMLParser | etree.HTMLParser
type _ParserOrParserClass = _LXMLParser | type[etree.XMLParser] | type[etree.HTMLParser]

class LXMLTreeBuilderForXML(TreeBuilder):
    DEFAULT_PARSER_CLASS: type[etree.XMLParser] = ...
    is_xml: bool = ...
    huge_tree: bool
    processing_instruction_class: type[ProcessingInstruction]
    NAME: str = ...
    ALTERNATE_NAMES: Iterable[str] = ...
    features: Iterable[str] = ...
    CHUNK_SIZE: int = ...
    DEFAULT_NSMAPS: _NamespaceMapping = ...
    DEFAULT_NSMAPS_INVERTED: _InvertedNamespaceMapping = ...
    nsmaps: list[_InvertedNamespaceMapping | None]
    empty_element_tags: set[str] | None
    parser: Any
    _default_parser: etree.XMLParser | None
    def initialize_soup(self, soup: BeautifulSoup) -> None:
        """Let the BeautifulSoup object know about the standard namespace
        mapping.

        :param soup: A `BeautifulSoup`.
        """
        ...

    def default_parser(self, encoding: _Encoding | None) -> _ParserOrParserClass:
        """Find the default parser for the given encoding.

        :return: Either a parser object or a class, which
          will be instantiated with default arguments.
        """
        ...

    def parser_for(self, encoding: _Encoding | None) -> _LXMLParser:
        """Instantiate an appropriate parser for the given encoding.

        :param encoding: A string.
        :return: A parser object such as an `etree.XMLParser`.
        """
        ...

    def __init__(
        self,
        parser: etree.XMLParser | None = ...,
        empty_element_tags: set[str] | None = ...,
        huge_tree: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def prepare_markup(
        self,
        markup: _RawMarkup,
        user_specified_encoding: _Encoding | None = ...,
        document_declared_encoding: _Encoding | None = ...,
        exclude_encodings: _Encodings | None = ...,
    ) -> Iterable[tuple[str | bytes, _Encoding | None, _Encoding | None, bool]]:
        """Run any preliminary steps necessary to make incoming markup
        acceptable to the parser.

        lxml really wants to get a bytestring and convert it to
        Unicode itself. So instead of using UnicodeDammit to convert
        the bytestring to Unicode using different encodings, this
        implementation uses EncodingDetector to iterate over the
        encodings, and tell lxml to try to parse the document as each
        one in turn.

        :param markup: Some markup -- hopefully a bytestring.
        :param user_specified_encoding: The user asked to try this encoding.
        :param document_declared_encoding: The markup itself claims to be
            in this encoding.
        :param exclude_encodings: The user asked _not_ to try any of
            these encodings.

        :yield: A series of 4-tuples: (markup, encoding, declared encoding,
            has undergone character replacement)

            Each 4-tuple represents a strategy for converting the
            document to Unicode and parsing it. Each strategy will be tried
            in turn.
        """
        ...

    def feed(self, markup: _RawMarkup) -> None: ...
    def close(self) -> None: ...
    def start(
        self,
        tag: str | bytes,
        attrib: dict[str | bytes, str | bytes],
        nsmap: _NamespaceMapping = ...,
    ) -> None: ...
    def end(self, tag: str | bytes) -> None: ...
    def pi(self, target: str, data: str) -> None: ...
    def data(self, data: str | bytes) -> None: ...
    def doctype(self, name: str, pubid: str, system: str) -> None: ...
    def comment(self, text: str | bytes) -> None:
        "Handle comments as Comment objects."
        ...

    def test_fragment_to_document(self, fragment: str) -> str:
        """See `TreeBuilder`."""
        ...

class LXMLTreeBuilder(HTMLTreeBuilder, LXMLTreeBuilderForXML):
    NAME: str = ...
    ALTERNATE_NAMES: Iterable[str] = ...
    features: Iterable[str] = ...
    is_xml: bool = ...
    def default_parser(self, encoding: _Encoding | None) -> _ParserOrParserClass: ...
    def feed(self, markup: _RawMarkup) -> None: ...
    def test_fragment_to_document(self, fragment: str) -> str:
        """See `TreeBuilder`."""
        ...
