"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common.webdriver import LocalWebDriver
from selenium.webdriver.wpewebkit.options import Options
from selenium.webdriver.wpewebkit.service import Service

class WebDriver(LocalWebDriver):
    """Controls the WPEWebKitDriver and allows you to drive the browser."""
    def __init__(self, options: Options | None = ..., service: Service | None = ...) -> None:
        """Creates a new instance of the WPEWebKit driver.

        Starts the service and then creates new instance of WPEWebKit Driver.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
        """
        ...
