"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping, Sequence
from pathlib import Path

"""Run a headless display inside X virtual framebuffer (Xvfb)."""

class Xvfb:
    MAX_DISPLAY = ...
    def __init__(
        self,
        width: int = ...,
        height: int = ...,
        colordepth: int = ...,
        tempdir: Path | str | None = ...,
        display: int | None = ...,
        set_xdg_session_type: bool = ...,
        environ: MutableMapping[str, str] | None = ...,
        extra_args: Sequence[str] | None = ...,
        timeout: int = ...,
        **kwargs,
    ) -> None: ...
    def __enter__(self) -> Xvfb: ...
    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
