"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

from selenium.webdriver.common.webdriver import LocalWebDriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

class WebDriver(LocalWebDriver):
    """Controls the GeckoDriver and allows you to drive the browser."""

    CONTEXT_CHROME = ...
    CONTEXT_CONTENT = ...
    def __init__(
        self, options: Options | None = ..., service: Service | None = ..., keep_alive: bool = ...
    ) -> None:
        """Create a new instance of the Firefox driver, start the service, and create new instance.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure FirefoxRemoteConnection to use HTTP keep-alive.
        """
        ...

    def set_context(self, context) -> None:
        """Sets the context that Selenium commands are running in.

        Args:
            context: Context to set, should be one of CONTEXT_CHROME or CONTEXT_CONTENT.
        """
        ...

    @contextmanager
    def context(self, context):  # -> Generator[None, Any, None]:
        """Set the context that Selenium commands are running in using a `with` statement.

        The state of the context on the server is saved before entering the block,
        and restored upon exiting it.

        Args:
            context: Context, may be one of the class properties
                `CONTEXT_CHROME` or `CONTEXT_CONTENT`.

        Example:
            with selenium.context(selenium.CONTEXT_CHROME):
                # chrome scope
                ... do stuff ...
        """
        ...

    def install_addon(self, path, temporary=...) -> str:
        """Installs Firefox addon.

        Returns identifier of installed addon. This identifier can later
        be used to uninstall addon.

        Args:
            path: Absolute path to the addon that will be installed.
            temporary: Allows you to load browser extensions temporarily during a session.

        Returns:
            Identifier of installed addon.

        Example:
            driver.install_addon("/path/to/firebug.xpi")
        """
        ...

    def uninstall_addon(self, identifier) -> None:
        """Uninstalls Firefox addon using its identifier.

        Args:
            identifier: The addon identifier to uninstall.

        Example:
            driver.uninstall_addon("addon@foo.com")
        """
        ...

    def get_full_page_screenshot_as_file(self, filename) -> bool:
        """Save a full document screenshot of the current window to a PNG image file.

        Args:
            filename: The full path you wish to save your screenshot to. This
                should end with a `.png` extension.

        Returns:
            False if there is any IOError, else returns True. Use full paths in your filename.

        Example:
            driver.get_full_page_screenshot_as_file("/Screenshots/foo.png")
        """
        ...

    def save_full_page_screenshot(self, filename) -> bool:
        """Save a full document screenshot of the current window to a PNG image file.

        Args:
            filename: The full path you wish to save your screenshot to. This
                should end with a `.png` extension.

        Returns:
            False if there is any IOError, else returns True. Use full paths in your filename.

        Example:
            driver.save_full_page_screenshot("/Screenshots/foo.png")
        """
        ...

    def get_full_page_screenshot_as_png(self) -> bytes:
        """Get the full document screenshot of the current window as binary data.

        Returns:
            Binary data of the screenshot.

        Example:
            driver.get_full_page_screenshot_as_png()
        """
        ...

    def get_full_page_screenshot_as_base64(self) -> str:
        """Get the full document screenshot of the current window as a base64-encoded string.

        Returns:
            Base64 encoded string of the screenshot.

        Example:
            driver.get_full_page_screenshot_as_base64()
        """
        ...
