"""
This type stub file was generated by pyright.
"""

from numpy._core.records import (
    array,
    find_duplicate,
    format_parser,
    fromarrays,
    fromfile,
    fromrecords,
    fromstring,
    recarray,
    record,
)

__all__ = [
    "array",
    "find_duplicate",
    "format_parser",
    "fromarrays",
    "fromfile",
    "fromrecords",
    "fromstring",
    "recarray",
    "record",
]
