"""
This type stub file was generated by pyright.
"""

from pandas._libs.lib import infer_dtype as infer_dtype
from pandas.core.dtypes.api import (
    is_any_real_numeric_dtype as is_any_real_numeric_dtype,
)
from pandas.core.dtypes.api import (
    is_bool as is_bool,
)
from pandas.core.dtypes.api import (
    is_bool_dtype as is_bool_dtype,
)
from pandas.core.dtypes.api import (
    is_complex as is_complex,
)
from pandas.core.dtypes.api import (
    is_complex_dtype as is_complex_dtype,
)
from pandas.core.dtypes.api import (
    is_datetime64_any_dtype as is_datetime64_any_dtype,
)
from pandas.core.dtypes.api import (
    is_datetime64_dtype as is_datetime64_dtype,
)
from pandas.core.dtypes.api import (
    is_datetime64_ns_dtype as is_datetime64_ns_dtype,
)
from pandas.core.dtypes.api import (
    is_dict_like as is_dict_like,
)
from pandas.core.dtypes.api import (
    is_dtype_equal as is_dtype_equal,
)
from pandas.core.dtypes.api import (
    is_extension_array_dtype as is_extension_array_dtype,
)
from pandas.core.dtypes.api import (
    is_file_like as is_file_like,
)
from pandas.core.dtypes.api import (
    is_float as is_float,
)
from pandas.core.dtypes.api import (
    is_float_dtype as is_float_dtype,
)
from pandas.core.dtypes.api import (
    is_hashable as is_hashable,
)
from pandas.core.dtypes.api import (
    is_integer as is_integer,
)
from pandas.core.dtypes.api import (
    is_integer_dtype as is_integer_dtype,
)
from pandas.core.dtypes.api import (
    is_iterator as is_iterator,
)
from pandas.core.dtypes.api import (
    is_list_like as is_list_like,
)
from pandas.core.dtypes.api import (
    is_named_tuple as is_named_tuple,
)
from pandas.core.dtypes.api import (
    is_number as is_number,
)
from pandas.core.dtypes.api import (
    is_numeric_dtype as is_numeric_dtype,
)
from pandas.core.dtypes.api import (
    is_object_dtype as is_object_dtype,
)
from pandas.core.dtypes.api import (
    is_re as is_re,
)
from pandas.core.dtypes.api import (
    is_re_compilable as is_re_compilable,
)
from pandas.core.dtypes.api import (
    is_scalar as is_scalar,
)
from pandas.core.dtypes.api import (
    is_signed_integer_dtype as is_signed_integer_dtype,
)
from pandas.core.dtypes.api import (
    is_string_dtype as is_string_dtype,
)
from pandas.core.dtypes.api import (
    is_timedelta64_dtype as is_timedelta64_dtype,
)
from pandas.core.dtypes.api import (
    is_timedelta64_ns_dtype as is_timedelta64_ns_dtype,
)
from pandas.core.dtypes.api import (
    is_unsigned_integer_dtype as is_unsigned_integer_dtype,
)
from pandas.core.dtypes.api import (
    pandas_dtype as pandas_dtype,
)
from pandas.core.dtypes.concat import union_categoricals as union_categoricals
from pandas.core.dtypes.dtypes import (
    CategoricalDtype as CategoricalDtype,
)
from pandas.core.dtypes.dtypes import (
    DatetimeTZDtype as DatetimeTZDtype,
)
from pandas.core.dtypes.dtypes import (
    IntervalDtype as IntervalDtype,
)
from pandas.core.dtypes.dtypes import (
    PeriodDtype as PeriodDtype,
)
