"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.chromium.webdriver import ChromiumDriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.edge.service import Service

class WebDriver(ChromiumDriver):
    """Controls the MSEdgeDriver and allows you to drive the browser."""
    def __init__(
        self, options: Options | None = ..., service: Service | None = ..., keep_alive: bool = ...
    ) -> None:
        """Creates a new instance of the edge driver.

        Starts the service and then creates new instance of edge driver.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure EdgeRemoteConnection to use HTTP keep-alive.
        """
        ...
