"""
This type stub file was generated by pyright.
"""

from ssl import _PeerCertRetDictType
from typing import Final

__version__: Final[str]

class CertificateError(ValueError): ...

def match_hostname(cert: _PeerCertRetDictType, hostname: str) -> None: ...
