"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.chromium.options import ChromiumOptions
from selenium.webdriver.chromium.service import ChromiumService
from selenium.webdriver.common.webdriver import LocalWebDriver

class ChromiumDriver(LocalWebDriver):
    """Control the WebDriver instance of ChromiumDriver and drive the browser."""
    def __init__(
        self,
        browser_name: str,
        vendor_prefix: str,
        options: ChromiumOptions | None = ...,
        service: ChromiumService | None = ...,
        keep_alive: bool = ...,
    ) -> None:
        """Create a new WebDriver instance, start the service, and create new ChromiumDriver instance.

        Args:
            browser_name: Browser name used when matching capabilities.
            vendor_prefix: Company prefix to apply to vendor-specific WebDriver extension commands.
            options: Instance of ChromiumOptions.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure ChromiumRemoteConnection to use HTTP keep-alive.
        """
        ...

    def launch_app(self, id):  # -> dict[str, Any]:
        """Launches Chromium app specified by id.

        Args:
            id: The id of the Chromium app to launch.
        """
        ...

    def get_network_conditions(self):  # -> Any:
        """Gets Chromium network emulation settings.

        Returns:
            A dict. For example: {'latency': 4, 'download_throughput': 2, 'upload_throughput': 2}
        """
        ...

    def set_network_conditions(self, **network_conditions) -> None:
        """Sets Chromium network emulation settings.

        Args:
            **network_conditions: A dict with conditions specification.

        Example:
            driver.set_network_conditions(
                offline=False,
                latency=5,  # additional latency (ms)
                download_throughput=500 * 1024,  # maximal throughput
                upload_throughput=500 * 1024,
            )  # maximal throughput

            Note: `throughput` can be used to set both (for download and upload).
        """
        ...

    def delete_network_conditions(self) -> None:
        """Resets Chromium network emulation settings."""
        ...

    def set_permissions(self, name: str, value: str) -> None:
        """Sets Applicable Permission.

        Args:
            name: The item to set the permission on.
            value: The value to set on the item

        Example:
            driver.set_permissions("clipboard-read", "denied")
        """
        ...

    def execute_cdp_cmd(self, cmd: str, cmd_args: dict):  # -> Any:
        """Execute Chrome Devtools Protocol command and get returned result.

        The command and command args should follow chrome devtools protocol domains/commands

        See:
          - https://chromedevtools.github.io/devtools-protocol/

        Args:
            cmd: A str, command name
            cmd_args: A dict, command args. empty dict {} if there is no command args

        Example:
            `driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': requestId})`

        Returns:
            A dict, empty dict {} if there is no result to return.
            For example to getResponseBody:
            {'base64Encoded': False, 'body': 'response body string'}
        """
        ...

    def get_sinks(self) -> list:
        """Get a list of sinks available for Cast."""
        ...

    def get_issue_message(self):  # -> Any:
        """Returns an error message when there is any issue in a Cast session."""
        ...

    @property
    def log_types(self):  # -> Any:
        """Gets a list of the available log types.

        Example:
        --------
        >>> driver.log_types
        """
        ...

    def get_log(self, log_type):  # -> Any:
        """Gets the log for a given log type.

        Args:
            log_type: Type of log that which will be returned

        Example:
            >>> driver.get_log("browser")
            >>> driver.get_log("driver")
            >>> driver.get_log("client")
            >>> driver.get_log("server")
        """
        ...

    def set_sink_to_use(self, sink_name: str) -> dict:
        """Set a specific sink as a Cast session receiver target.

        Args:
            sink_name: Name of the sink to use as the target.
        """
        ...

    def start_desktop_mirroring(self, sink_name: str) -> dict:
        """Starts a desktop mirroring session on a specific receiver target.

        Args:
            sink_name: Name of the sink to use as the target.
        """
        ...

    def start_tab_mirroring(self, sink_name: str) -> dict:
        """Starts a tab mirroring session on a specific receiver target.

        Args:
            sink_name: Name of the sink to use as the target.
        """
        ...

    def stop_casting(self, sink_name: str) -> dict:
        """Stops the existing Cast session on a specific receiver target.

        Args:
            sink_name: Name of the sink to stop the Cast session.
        """
        ...
