"""
This type stub file was generated by pyright.
"""

import datetime
import sys
from builtins import type as type_t
from collections.abc import (
    Callable,
    Hashable,
    Iterator,
    KeysView,
    Mapping,
    MutableSequence,
    Sequence,
)
from datetime import tzinfo
from os import PathLike
from re import Pattern
from typing import (
    TYPE_CHECKING,
    Any,
    Generic,
    Literal,
    ParamSpec,
    Protocol,
    SupportsIndex,
    TypeAlias,
    TypedDict,
    TypeVar,
    overload,
    override,
)

import numpy as np
import pandas as pd
from numpy import typing as npt
from pandas._libs.interval import Interval
from pandas._libs.missing import NAType
from pandas._libs.tslibs import BaseOffset, Period, Timedelta, Timestamp
from pandas._libs.tslibs.nattype import NaTType
from pandas.core.arrays import ExtensionArray, IntegerArray
from pandas.core.dtypes.dtypes import CategoricalDtype, ExtensionDtype
from pandas.core.frame import DataFrame
from pandas.core.generic import NDFrame
from pandas.core.groupby.grouper import Grouper
from pandas.core.indexes.base import Index
from pandas.core.series import Series
from pandas.core.tools.datetimes import FulldatetimeDict
from pandas.io.formats.format import EngFormatter
from pandas.tseries.offsets import (
    Day,
    Hour,
    Micro,
    Milli,
    Minute,
    MonthEnd,
    Nano,
    QuarterEnd,
    Second,
    Week,
    YearEnd,
)

P = ParamSpec("P")
HashableT = TypeVar("HashableT", bound=Hashable)
HashableT1 = TypeVar("HashableT1", bound=Hashable)
HashableT2 = TypeVar("HashableT2", bound=Hashable)
HashableT3 = TypeVar("HashableT3", bound=Hashable)
HashableT4 = TypeVar("HashableT4", bound=Hashable)
HashableT5 = TypeVar("HashableT5", bound=Hashable)
type ArrayLike = ExtensionArray | npt.NDArray[Any]
type AnyArrayLike = ArrayLike | Index | Series
if TYPE_CHECKING:
    type AnyArrayLikeInt = IntegerArray | Index[int] | Series[int] | npt.NDArray[np.integer]
_T_co = TypeVar("_T_co", covariant=True)
_T_contra = TypeVar("_T_contra", contravariant=True)

class SequenceNotStr(Protocol[_T_co]):
    @overload
    def __getitem__(self, index: SupportsIndex, /) -> _T_co: ...
    @overload
    def __getitem__(self, index: slice, /) -> Sequence[_T_co]: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def index(self, value: Any, start: int = ..., stop: int = ..., /) -> int: ...
    def count(self, value: Any, /) -> int: ...
    def __reversed__(self) -> Iterator[_T_co]: ...

type ListLike = AnyArrayLike | SequenceNotStr[Any] | range
type PythonScalar = str | bool | complex
type DatetimeLikeScalar = Period | Timestamp | Timedelta
type PandasScalar = Period | Timestamp | Timedelta | Interval
type _IndexIterScalar = (
    str
    | bytes
    | datetime.date
    | datetime.datetime
    | datetime.timedelta
    | np.datetime64
    | np.timedelta64
    | bool
    | int
    | float
    | Timestamp
    | Timedelta
)
type Scalar = _IndexIterScalar | complex | np.integer | np.floating | np.complexfloating
type ScalarOrNA = Scalar | NAType | NaTType | None
IntStrT = TypeVar("IntStrT", int, str)
type TimestampConvertibleTypes = (
    Timestamp | datetime.datetime | datetime.date | np.datetime64 | np.integer | float | str
)
type TimestampNonexistent = (
    Literal["shift_forward", "shift_backward", "NaT", "raise"] | Timedelta | datetime.timedelta
)
type TimedeltaConvertibleTypes = (
    Timedelta | datetime.timedelta | np.timedelta64 | np.integer | float | str
)
type Timezone = str | tzinfo
type ToTimestampHow = Literal["s", "e", "start", "end"]
NDFrameT = TypeVar("NDFrameT", bound=NDFrame)
IndexT = TypeVar("IndexT", bound=Index)
T_EXTENSION_ARRAY = TypeVar("T_EXTENSION_ARRAY", bound=ExtensionArray)
type AxisInt = int
type AxisIndex = Literal["index", 0]
type AxisColumn = Literal["columns", 1]
type Axis = AxisIndex | AxisColumn
type IndexLabel = Hashable | Sequence[Hashable]
type Level = Hashable
type Shape = tuple[int, ...]
type Suffixes = tuple[str | None, str | None] | list[str | None]
type Ordered = bool | None
type JSONSerializable = PythonScalar | list[Any] | dict[str, Any]
type Frequency = str | BaseOffset
type PeriodFrequency = (
    str
    | Day
    | Hour
    | Minute
    | Second
    | Milli
    | Micro
    | Nano
    | YearEnd
    | QuarterEnd
    | MonthEnd
    | Week
)
type Axes = ListLike
type RandomState = (
    int | ArrayLike | np.random.Generator | np.random.BitGenerator | np.random.RandomState
)
type NpDtypeNoStr = np.dtype[np.generic] | type[complex | bool | object]
type NpDtype = str | NpDtypeNoStr | type[str]
type Dtype = ExtensionDtype | NpDtype
type BuiltinBooleanDtypeArg = type[bool] | Literal["bool"]
type PandasBooleanDtypeArg = pd.BooleanDtype | Literal["boolean"]
type NumpyBooleanDtypeArg = type[np.bool_] | Literal["?", "b1", "bool_"]
type PyArrowBooleanDtypeArg = Literal["bool[pyarrow]", "boolean[pyarrow]"]
type BooleanDtypeArg = (
    BuiltinBooleanDtypeArg | PandasBooleanDtypeArg | NumpyBooleanDtypeArg | PyArrowBooleanDtypeArg
)
type BuiltinIntDtypeArg = type[int] | Literal["int"]
type PandasIntDtypeArg = (
    pd.Int8Dtype
    | pd.Int16Dtype
    | pd.Int32Dtype
    | pd.Int64Dtype
    | Literal["Int8", "Int16", "Int32", "Int64"]
)
type NumpyIntDtypeArg = (
    type[np.byte]
    | Literal["b", "i1", "int8", "byte"]
    | type[np.short]
    | Literal["h", "i2", "int16", "short"]
    | type[np.intc]
    | Literal["i", "i4", "int32", "intc"]
    | type[np.int_]
    | Literal["l", "i8", "int64", "int_", "long"]
    | type[np.longlong]
    | Literal["q", "longlong"]
    | type[np.intp]
    | Literal["p", "intp"]
)
type PyArrowIntDtypeArg = Literal[
    "int8[pyarrow]", "int16[pyarrow]", "int32[pyarrow]", "int64[pyarrow]"
]
type IntDtypeArg = BuiltinIntDtypeArg | PandasIntDtypeArg | NumpyIntDtypeArg | PyArrowIntDtypeArg
type PandasUIntDtypeArg = (
    pd.UInt8Dtype
    | pd.UInt16Dtype
    | pd.UInt32Dtype
    | pd.UInt64Dtype
    | Literal["UInt8", "UInt16", "UInt32", "UInt64"]
)
type NumpyUIntDtypeArg = (
    type[np.ubyte]
    | Literal["B", "u1", "uint8", "ubyte"]
    | type[np.ushort]
    | Literal["H", "u2", "uint16", "ushort"]
    | type[np.uintc]
    | Literal["I", "u4", "uint32", "uintc"]
    | type[np.uint]
    | Literal["L", "u8", "uint", "ulong", "uint64"]
    | type[np.ulonglong]
    | Literal["Q", "ulonglong"]
    | type[np.uintp]
    | Literal["P", "uintp"]
)
type PyArrowUIntDtypeArg = Literal[
    "uint8[pyarrow]", "uint16[pyarrow]", "uint32[pyarrow]", "uint64[pyarrow]"
]
type UIntDtypeArg = PandasUIntDtypeArg | NumpyUIntDtypeArg | PyArrowUIntDtypeArg
type BuiltinFloatDtypeArg = type[float] | Literal["float"]
type PandasFloatDtypeArg = pd.Float32Dtype | pd.Float64Dtype | Literal["Float32", "Float64"]
type PandasAstypeFloatDtypeArg = Literal["float_", "longfloat"]
type NumpyFloat16DtypeArg = type[np.half] | Literal["e", "f2", "<f2", "float16", "half"]
type NumpyFloatNot16DtypeArg = (
    type[np.single]
    | Literal["f", "f4", "float32", "single"]
    | type[np.double]
    | Literal["d", "f8", "float64", "double"]
    | type[np.longdouble]
    | Literal["g", "f16", "float128", "longdouble"]
)
type PyArrowFloatDtypeArg = Literal[
    "float[pyarrow]",
    "double[pyarrow]",
    "float16[pyarrow]",
    "float32[pyarrow]",
    "float64[pyarrow]",
]
type FloatDtypeArg = (
    BuiltinFloatDtypeArg
    | PandasFloatDtypeArg
    | NumpyFloat16DtypeArg
    | NumpyFloatNot16DtypeArg
    | PyArrowFloatDtypeArg
)
type BuiltinComplexDtypeArg = type[complex] | Literal["complex"]
type PandasAstypeComplexDtypeArg = (
    Literal["singlecomplex"]
    | Literal["cfloat", "complex_"]
    | Literal["c32", "complex256", "clongfloat", "longcomplex"]
)
type NumpyComplexDtypeArg = (
    type[np.csingle]
    | Literal["F", "c8", "complex64", "csingle"]
    | type[np.cdouble]
    | Literal["D", "c16", "complex128", "cdouble"]
    | type[np.clongdouble]
    | Literal["G", "clongdouble"]
)
type ComplexDtypeArg = BuiltinComplexDtypeArg | NumpyComplexDtypeArg
type PandasAstypeTimedeltaDtypeArg = Literal[
    "timedelta64[Y]",
    "timedelta64[M]",
    "timedelta64[W]",
    "timedelta64[D]",
    "timedelta64[h]",
    "timedelta64[m]",
    "timedelta64[μs]",
    "timedelta64[ps]",
    "timedelta64[fs]",
    "timedelta64[as]",
    "m8[Y]",
    "m8[M]",
    "m8[W]",
    "m8[D]",
    "m8[h]",
    "m8[m]",
    "m8[μs]",
    "m8[ps]",
    "m8[fs]",
    "m8[as]",
    "<m8[Y]",
    "<m8[M]",
    "<m8[W]",
    "<m8[D]",
    "<m8[h]",
    "<m8[m]",
    "<m8[μs]",
    "<m8[ps]",
    "<m8[fs]",
    "<m8[as]",
]
type NumpyTimedeltaDtypeArg = Literal[
    "timedelta64[s]",
    "timedelta64[ms]",
    "timedelta64[us]",
    "timedelta64[ns]",
    "m8[s]",
    "m8[ms]",
    "m8[us]",
    "m8[ns]",
    "<m8[s]",
    "<m8[ms]",
    "<m8[us]",
    "<m8[ns]",
]
type PyArrowTimedeltaDtypeArg = Literal[
    "duration[s][pyarrow]",
    "duration[ms][pyarrow]",
    "duration[us][pyarrow]",
    "duration[ns][pyarrow]",
]
type TimedeltaDtypeArg = NumpyTimedeltaDtypeArg | PyArrowTimedeltaDtypeArg
type PandasTimestampDtypeArg = (
    pd.DatetimeTZDtype
    | Literal[
        "datetime64[s, UTC]",
        "datetime64[ms, UTC]",
        "datetime64[us, UTC]",
        "datetime64[ns, UTC]",
    ]
)
type PandasAstypeTimestampDtypeArg = Literal[
    "datetime64[Y]",
    "datetime64[M]",
    "datetime64[W]",
    "datetime64[D]",
    "datetime64[h]",
    "datetime64[m]",
    "datetime64[μs]",
    "datetime64[ps]",
    "datetime64[fs]",
    "datetime64[as]",
    "M8[Y]",
    "M8[M]",
    "M8[W]",
    "M8[D]",
    "M8[h]",
    "M8[m]",
    "M8[μs]",
    "M8[ps]",
    "M8[fs]",
    "M8[as]",
    "<M8[Y]",
    "<M8[M]",
    "<M8[W]",
    "<M8[D]",
    "<M8[h]",
    "<M8[m]",
    "<M8[μs]",
    "<M8[ps]",
    "<M8[fs]",
    "<M8[as]",
]
type NumpyTimestampDtypeArg = Literal[
    "datetime64[s]",
    "datetime64[ms]",
    "datetime64[us]",
    "datetime64[ns]",
    "M8[s]",
    "M8[ms]",
    "M8[us]",
    "M8[ns]",
    "<M8[s]",
    "<M8[ms]",
    "<M8[us]",
    "<M8[ns]",
]
type PyArrowTimestampDtypeArg = Literal[
    "date32[pyarrow]",
    "date64[pyarrow]",
    "timestamp[s][pyarrow]",
    "timestamp[ms][pyarrow]",
    "timestamp[us][pyarrow]",
    "timestamp[ns][pyarrow]",
]
type TimestampDtypeArg = PandasTimestampDtypeArg | NumpyTimestampDtypeArg | PyArrowTimestampDtypeArg
type BuiltinStrDtypeArg = type[str] | Literal["str"]
type PandasStrDtypeArg = pd.StringDtype | Literal["string"]
type NumpyStrDtypeArg = type[np.str_] | Literal["U", "str_", "unicode"]
type PyArrowStrDtypeArg = Literal["string[pyarrow]"]
type StrDtypeArg = BuiltinStrDtypeArg | PandasStrDtypeArg | NumpyStrDtypeArg | PyArrowStrDtypeArg
type BuiltinBytesDtypeArg = type[bytes] | Literal["bytes"]
type NumpyBytesDtypeArg = type[np.bytes_] | Literal["S", "bytes_"]
type PyArrowBytesDtypeArg = Literal["binary[pyarrow]"]
type BytesDtypeArg = BuiltinBytesDtypeArg | NumpyBytesDtypeArg | PyArrowBytesDtypeArg
type CategoryDtypeArg = CategoricalDtype | Literal["category"]
type BuiltinObjectDtypeArg = type[object] | Literal["object"]
type NumpyObjectDtypeArg = type[np.object_] | Literal["O"]
type ObjectDtypeArg = BuiltinObjectDtypeArg | NumpyObjectDtypeArg
type NumpyVoidDtypeArg = type[np.void] | Literal["V", "void"]
type VoidDtypeArg = NumpyVoidDtypeArg
type DtypeArg = Dtype | Mapping[Hashable, Dtype]
type DtypeObj = np.dtype[np.generic] | ExtensionDtype
type AstypeArg = (
    BooleanDtypeArg
    | IntDtypeArg
    | UIntDtypeArg
    | StrDtypeArg
    | BytesDtypeArg
    | FloatDtypeArg
    | ComplexDtypeArg
    | TimedeltaDtypeArg
    | TimestampDtypeArg
    | CategoryDtypeArg
    | ObjectDtypeArg
    | VoidDtypeArg
    | DtypeObj
)
type ConvertersArg = Mapping[Hashable, Callable[[Dtype], Dtype]]
type ParseDatesArg[HashableT: Hashable, HashableT2: Hashable] = (
    bool | list[Hashable] | list[list[Hashable]] | Mapping[HashableT, list[HashableT2]]
)
type Label = Hashable | None
type Renamer = Mapping[Any, Label] | Callable[[Any], Label]
T = TypeVar("T")
type FuncType = Callable[..., Any]
F = TypeVar("F", bound=FuncType)
TypeT = TypeVar("TypeT", bound=type)
type ValueKeyFunc = Callable[[Series], Series | AnyArrayLike] | None
type IndexKeyFunc = Callable[[Index], Index | AnyArrayLike] | None
type AggFuncTypeBase[**P] = Callable[P, Any] | str | np.ufunc
type AggFuncTypeDictSeries[HashableT: Hashable, **P] = Mapping[HashableT, AggFuncTypeBase[P]]
type AggFuncTypeDictFrame[HashableT: Hashable, **P] = Mapping[
    HashableT, AggFuncTypeBase[P] | Sequence[AggFuncTypeBase[P]]
]
type AggFuncTypeSeriesToFrame[**P, HashableT: Hashable] = (
    Sequence[AggFuncTypeBase[P]] | AggFuncTypeDictSeries[HashableT, P]
)
type AggFuncTypeFrame[**P, HashableT: Hashable] = (
    AggFuncTypeBase[P] | Sequence[AggFuncTypeBase[P]] | AggFuncTypeDictFrame[HashableT, P]
)
type AggFuncTypeDict[HashableT: Hashable, **P] = (
    AggFuncTypeDictSeries[HashableT, P] | AggFuncTypeDictFrame[HashableT, P]
)
type AggFuncType[**P, HashableT: Hashable] = (
    AggFuncTypeBase[P] | Sequence[AggFuncTypeBase[P]] | AggFuncTypeDict[HashableT, P]
)
AnyStr_co = TypeVar("AnyStr_co", str, bytes, covariant=True)
AnyStr_contra = TypeVar("AnyStr_contra", str, bytes, contravariant=True)

class BaseBuffer(Protocol):
    @property
    def mode(self) -> str: ...
    def seek(self, offset: int, whence: int = ..., /) -> int: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...

class ReadBuffer(BaseBuffer, Protocol[AnyStr_co]):
    def read(self, n: int = ..., /) -> AnyStr_co: ...

class WriteBuffer(BaseBuffer, Protocol[AnyStr_contra]):
    def write(self, b: AnyStr_contra, /) -> Any: ...
    def flush(self) -> Any: ...

class ReadPickleBuffer(ReadBuffer[bytes], Protocol):
    def readline(self) -> bytes: ...

class WriteExcelBuffer(WriteBuffer[bytes], Protocol):
    def truncate(self, size: int | None = ..., /) -> int: ...

class ReadCsvBuffer(ReadBuffer[AnyStr_co], Protocol):
    def __iter__(self) -> Iterator[AnyStr_co]: ...
    def fileno(self) -> int: ...
    def readline(self) -> AnyStr_co: ...
    @property
    def closed(self) -> bool: ...

type FilePath = str | PathLike[str]
type StorageOptions = dict[str, Any] | None
type CompressionDict = dict[str, Any]
type CompressionOptions = (
    None | Literal["infer", "gzip", "bz2", "zip", "xz", "zstd", "tar"] | CompressionDict
)
type FormattersType = (
    list[Callable[..., Any]]
    | tuple[Callable[..., Any], ...]
    | Mapping[str | int, Callable[..., Any]]
)
type FloatFormatType = str | Callable[[float], str] | EngFormatter
type ColspaceArgType = str | int | Sequence[int | str] | Mapping[Hashable, str | int]
type FillnaOptions = Literal["backfill", "bfill", "ffill", "pad"]
type InterpolateOptions = Literal[
    "linear",
    "time",
    "index",
    "values",
    "nearest",
    "zero",
    "slinear",
    "quadratic",
    "cubic",
    "barycentric",
    "polynomial",
    "krogh",
    "piecewise_polynomial",
    "spline",
    "pchip",
    "akima",
    "cubicspline",
    "from_derivatives",
]
type ScalarIndexer = int | np.integer
type SequenceIndexer = slice | list[int] | npt.NDArray[np.integer | np.bool]
type PositionalIndexer = ScalarIndexer | SequenceIndexer
type PositionalIndexerTuple = tuple[PositionalIndexer, PositionalIndexer]
type TakeIndexer = Sequence[int | np.integer] | npt.NDArray[np.integer | np.bool]
type IgnoreRaise = Literal["ignore", "raise"]
type WindowingRankType = Literal["average", "min", "max"]
type CSVEngine = Literal["c", "python", "pyarrow", "python-fwf"]
type JSONEngine = Literal["ujson", "pyarrow"]
type XMLParsers = Literal["lxml", "etree"]
type HTMLFlavors = Literal["lxml", "html5lib", "bs4"]
IntervalT = TypeVar("IntervalT", bound=Interval)
type IntervalLeftRight = Literal["left", "right"]
type IntervalClosedType = IntervalLeftRight | Literal["both", "neither"]
type RaiseCoerce = Literal["raise", "coerce"]
type DateTimeErrorChoices = RaiseCoerce
type SortKind = Literal["quicksort", "mergesort", "heapsort", "stable"]
type NaPosition = Literal["first", "last"]
type NsmallestNlargestKeep = Literal["first", "last", "all"]
type QuantileInterpolation = Literal["linear", "lower", "higher", "midpoint", "nearest"]
type AnyAll = Literal["any", "all"]
type JoinHow = Literal["left", "right", "outer", "inner"]
type MergeHow = JoinHow | Literal["cross", "left_anti", "right_anti"]
type ValidationOptions = Literal[
    "one_to_one",
    "1:1",
    "one_to_many",
    "1:m",
    "many_to_one",
    "m:1",
    "many_to_many",
    "m:m",
]
type MergeValidate = ValidationOptions
type JoinValidate = ValidationOptions
type ReindexMethod = FillnaOptions | Literal["nearest"]
type TimeGrouperOrigin = Timestamp | Literal["epoch", "start", "start_day", "end", "end_day"]
type TimeAmbiguous = Literal["infer", "NaT", "raise"] | npt.NDArray[np.bool_]
type TimeNonexistent = (
    Literal["shift_forward", "shift_backward", "NaT", "raise"] | Timedelta | datetime.timedelta
)
type DropKeep = Literal["first", "last", False]
type CorrelationMethod = (
    Literal["pearson", "kendall", "spearman"]
    | Callable[[npt.NDArray[Any], npt.NDArray[Any]], float]
)
type AlignJoin = Literal["outer", "inner", "left", "right"]
type DtypeBackend = Literal["pyarrow", "numpy_nullable"]
type TimeUnit = Literal["s", "ms", "us", "ns"]
type OpenFileErrors = Literal[
    "strict",
    "ignore",
    "replace",
    "surrogateescape",
    "xmlcharrefreplace",
    "backslashreplace",
    "namereplace",
]
type UpdateJoin = Literal["left"]
type FromDictOrient = Literal["columns", "index", "tight"]
type ToStataByteorder = Literal[">", "<", "little", "big"]
type ExcelWriterIfSheetExists = Literal["error", "new", "replace", "overlay"]
type ExcelWriterMergeCells = bool | Literal["columns"]
type UsecolsArgType[HashableT: Hashable] = (
    SequenceNotStr[Hashable] | range | AnyArrayLike | Callable[[HashableT], bool] | None
)
type SliceType = Hashable | None
type BuiltinDtypeArg = (
    BuiltinBooleanDtypeArg
    | BuiltinIntDtypeArg
    | BuiltinFloatDtypeArg
    | BuiltinComplexDtypeArg
    | BuiltinStrDtypeArg
    | BuiltinBytesDtypeArg
    | BuiltinObjectDtypeArg
)
type NumpyNotTimeDtypeArg = (
    NumpyBooleanDtypeArg
    | NumpyIntDtypeArg
    | NumpyUIntDtypeArg
    | NumpyFloat16DtypeArg
    | NumpyFloatNot16DtypeArg
    | NumpyComplexDtypeArg
    | NumpyStrDtypeArg
    | NumpyBytesDtypeArg
    | NumpyObjectDtypeArg
    | NumpyVoidDtypeArg
)
type PyArrowNotStrDtypeArg = (
    PyArrowBooleanDtypeArg
    | PyArrowIntDtypeArg
    | PyArrowUIntDtypeArg
    | PyArrowFloatDtypeArg
    | PyArrowTimedeltaDtypeArg
    | PyArrowTimestampDtypeArg
    | PyArrowBytesDtypeArg
)
type StrLike = str | np.str_
ScalarT = TypeVar("ScalarT", bound=Scalar)
type np_num = np.bool | np.integer | np.floating | np.complexfloating
type np_ndarray_intp = npt.NDArray[np.intp]
type np_ndarray_int64 = npt.NDArray[np.int64]
type np_ndarray_int = npt.NDArray[np.signedinteger]
type np_ndarray_anyint = npt.NDArray[np.integer]
type np_ndarray_float = npt.NDArray[np.floating]
type np_ndarray_complex = npt.NDArray[np.complexfloating]
type np_ndarray_bool = npt.NDArray[np.bool_]
type np_ndarray_str = npt.NDArray[np.str_]
type np_ndarray_dt = npt.NDArray[np.datetime64]
type np_ndarray_td = npt.NDArray[np.timedelta64]
GenericT = TypeVar("GenericT", bound=np.generic, default=Any)
GenericT_co = TypeVar("GenericT_co", bound=np.generic, default=Any, covariant=True)
GenericT_contra = TypeVar("GenericT_contra", bound=np.generic, default=Any, contravariant=True)
NpNumT = TypeVar("NpNumT", bound=np_num, default=np_num)
ShapeT = TypeVar("ShapeT", bound=tuple[int, ...], default=tuple[Any, ...])
np_ndarray: TypeAlias = np.ndarray[ShapeT, np.dtype[GenericT]]
np_ndarray_num: TypeAlias = np_ndarray[ShapeT, NpNumT]
np_1darray: TypeAlias = np.ndarray[tuple[int], np.dtype[GenericT]]
type np_1darray_str = np_1darray[np.str_]
type np_1darray_bytes = np_1darray[np.bytes_]
type np_1darray_complex = np_1darray[np.complexfloating]
type np_1darray_object = np_1darray[np.object_]
type np_1darray_bool = np_1darray[np.bool]
type np_1darray_intp = np_1darray[np.intp]
type np_1darray_int8 = np_1darray[np.int8]
type np_1darray_int64 = np_1darray[np.int64]
type np_1darray_anyint = np_1darray[np.integer]
type np_1darray_float = np_1darray[np.floating]
type np_1darray_dt = np_1darray[np.datetime64]
type np_1darray_td = np_1darray[np.timedelta64]
np_2darray: TypeAlias = np.ndarray[tuple[int, int], np.dtype[GenericT]]
if sys.version_info >= (3, 11):
    NDArrayT = TypeVar("NDArrayT", bound=np.ndarray)
else: ...
DtypeNp = TypeVar("DtypeNp", bound=np.dtype[np.generic])
type KeysArgType = Any
ListLikeT = TypeVar("ListLikeT", bound=ListLike)
type ListLikeExceptSeriesAndStr = MutableSequence[Any] | np_1darray | tuple[Any, ...] | Index
type ListLikeU = Sequence[Any] | np_1darray | Series | Index
type ListLikeHashable[HashableT: Hashable] = (
    MutableSequence[HashableT] | np_1darray | tuple[HashableT, ...] | range
)

class SupportsDType(Protocol[GenericT_co]):
    @property
    def dtype(self) -> np.dtype[GenericT_co]: ...

type DTypeLike = type[Any] | tuple[Any, Any] | list[Any] | str
if TYPE_CHECKING:
    type IndexType = slice | np_ndarray_anyint | Index | list[int] | Series[int]
    type MaskType = Series[bool] | np_ndarray_bool | list[bool]
T_INT = TypeVar("T_INT", bound=int)
T_COMPLEX = TypeVar("T_COMPLEX", bound=complex)
type SeriesDTypeNoStrDateTime = (
    bytes
    | bool
    | int
    | float
    | complex
    | NpDtypeNoStr
    | ExtensionDtype
    | Period
    | Interval
    | CategoricalDtype
    | BaseOffset
)
type SeriesDTypeNoDateTime = str | SeriesDTypeNoStrDateTime | type[str] | list[str]
type SeriesDType = (
    SeriesDTypeNoDateTime | datetime.date | datetime.time | datetime.datetime | datetime.timedelta
)
S1 = TypeVar("S1", bound=SeriesDType, default=Any)
S2 = TypeVar("S2", bound=SeriesDType)
S2_contra = TypeVar("S2_contra", bound=SeriesDType, contravariant=True)
S2_NDT_contra = TypeVar("S2_NDT_contra", bound=SeriesDTypeNoDateTime, contravariant=True)
S2_NSDT = TypeVar("S2_NSDT", bound=SeriesDTypeNoStrDateTime)
S3 = TypeVar("S3", bound=SeriesDType)
C2 = TypeVar(
    "C2",
    str,
    bytes,
    datetime.date,
    datetime.time,
    bool,
    int,
    float,
    complex,
    Dtype,
    datetime.datetime,
    datetime.timedelta,
    Period,
    Interval,
    CategoricalDtype,
    BaseOffset,
)
type IndexingInt = int | np.int_ | np.integer | np.unsignedinteger | np.signedinteger | np.int8
type AxesData[S3: SeriesDType] = Mapping[S3, Any] | Axes | KeysView[S3]
type Function = np.ufunc | Callable[..., Any]
_HashableTa = TypeVar("_HashableTa", bound=Hashable)
if TYPE_CHECKING:
    ByT = TypeVar(
        "ByT",
        bound=str
        | bytes
        | datetime.date
        | datetime.datetime
        | datetime.timedelta
        | np.datetime64
        | np.timedelta64
        | bool
        | int
        | float
        | complex
        | Scalar
        | Period
        | Interval[int | float | Timestamp | Timedelta]
        | tuple,
    )
    SeriesByT = TypeVar(
        "SeriesByT",
        bound=str
        | bytes
        | datetime.date
        | bool
        | int
        | float
        | complex
        | datetime.datetime
        | datetime.timedelta
        | Period
        | Interval[int | float | Timestamp | Timedelta],
    )
type GroupByObjectNonScalar[_HashableTa: Hashable] = (
    tuple[_HashableTa, ...]
    | list[_HashableTa]
    | Function
    | list[Function]
    | list[Series]
    | np_ndarray
    | list[np_ndarray]
    | Mapping[Label, Any]
    | list[Mapping[Label, Any]]
    | list[Index]
    | Grouper
    | list[Grouper]
)
type GroupByObject = Scalar | Index | GroupByObjectNonScalar | Series
type StataDateFormat = Literal[
    "tc",
    "%tc",
    "td",
    "%td",
    "tw",
    "%tw",
    "tm",
    "%tm",
    "tq",
    "%tq",
    "th",
    "%th",
    "ty",
    "%ty",
]
type ReplaceValue[HashableT: Hashable, ScalarT: Scalar] = (
    Scalar
    | Pattern
    | NAType
    | Sequence[Scalar | Pattern]
    | Mapping[HashableT, ScalarT]
    | Series
    | None
)
type JsonFrameOrient = Literal["split", "records", "index", "columns", "values", "table"]
type JsonSeriesOrient = Literal["split", "records", "index", "table"]
type TimestampConvention = Literal["start", "end", "s", "e"]
type CSVQuotingCompat = Literal[0, 1, 2, 3]
if sys.version_info >= (3, 12):
    type CSVQuoting = CSVQuotingCompat | Literal[4, 5]
else: ...
type HDFCompLib = Literal["zlib", "lzo", "bzip2", "blosc"]
type ParquetEngine = Literal["auto", "pyarrow", "fastparquet"]
type FileWriteMode = Literal[
    "a", "w", "x", "at", "wt", "xt", "ab", "wb", "xb", "w+", "w+b", "a+", "a+b"
]
type WindowingEngine = Literal["cython", "numba"] | None

class _WindowingNumbaKwargs(TypedDict, total=False):
    nopython: bool
    nogil: bool
    parallel: bool
    ...

type WindowingEngineKwargs = _WindowingNumbaKwargs | None

class StyleExportDict(TypedDict, total=False):
    apply: Any
    table_attributes: Any
    table_styles: Any
    hide_index: bool
    hide_columns: bool
    hide_index_names: bool
    hide_column_names: bool
    css: dict[str, str | int]
    ...

type CalculationMethod = Literal["single", "table"]
type ExcelReadEngine = Literal["xlrd", "openpyxl", "odf", "pyxlsb", "calamine"]
type ExcelWriteEngine = Literal["openpyxl", "odf", "xlsxwriter"]
type TimeZones = str | tzinfo | None | int
type IntoColumn = (
    AnyArrayLike
    | Scalar
    | Callable[[DataFrame], AnyArrayLike | Scalar | Sequence[Scalar] | range | None]
    | Sequence[Scalar]
    | range
    | None
)
type DatetimeLike = datetime.datetime | np.datetime64 | Timestamp
type DateAndDatetimeLike = datetime.date | DatetimeLike
type DatetimeDictArg = (
    Sequence[int] | Sequence[float] | list[str] | tuple[Scalar, ...] | AnyArrayLike
)
type DictConvertible = FulldatetimeDict | DataFrame
type Incomplete = Any

class Just(Protocol, Generic[T]):
    @property
    @override
    def __class__(self, /) -> type[T]: ...
    @__class__.setter
    @override
    def __class__(self, t: type[T], /) -> None: ...

class SupportsTrueDiv(Protocol[_T_contra, _T_co]):
    def __truediv__(self, x: _T_contra, /) -> _T_co: ...

class SupportsRTrueDiv(Protocol[_T_contra, _T_co]):
    def __rtruediv__(self, x: _T_contra, /) -> _T_co: ...

__all__ = ["npt", "type_t"]
