"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common.webdriver import LocalWebDriver
from selenium.webdriver.safari.options import Options
from selenium.webdriver.safari.service import Service

class WebDriver(LocalWebDriver):
    """Controls the SafariDriver and allows you to drive the browser."""
    def __init__(
        self, options: Options | None = ..., service: Service | None = ..., keep_alive: bool = ...
    ) -> None:
        """Create a new Safari driver instance and launch or find a running safaridriver service.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure SafariRemoteConnection to use HTTP keep-alive.
        """
        ...

    def quit(self):  # -> None:
        """Closes the browser and shuts down the SafariDriver executable."""
        ...

    def set_permission(self, permission, value):  # -> None:
        ...
    def get_permission(self, permission):  # -> bool | None:
        ...
    def debug(self):  # -> None:
        ...
