"""
This type stub file was generated by pyright.
"""

import enum
from typing import Final, final

__all__ = ["_CopyMode", "_NoValue"]

@final
class _CopyMode(enum.Enum):
    ALWAYS = ...
    NEVER = ...
    IF_NEEDED = ...
    def __bool__(self, /) -> bool: ...

@final
class _NoValueType: ...

_NoValue: Final[_NoValueType] = ...
