"""
This type stub file was generated by pyright.
"""

import numpy as np
from pandas import DataFrame, Index, Series
from pandas._typing import ArrayLike, np_1darray

def hash_pandas_object(
    obj: Index | Series | DataFrame,
    index: bool = ...,
    encoding: str = ...,
    hash_key: str | None = ...,
    categorize: bool = ...,
) -> Series[int]: ...
def hash_array(
    vals: ArrayLike, encoding: str = ..., hash_key: str = ..., categorize: bool = ...
) -> np_1darray[np.uint64]: ...
