"""
This type stub file was generated by pyright.
"""

from typing import NoReturn, overload

from selenium.webdriver.common.by import ByType
from selenium.webdriver.remote.webelement import WebElement

def with_tag_name(tag_name: str) -> RelativeBy:
    """Start searching for relative objects using a tag name.

    Args:
        tag_name: The DOM tag of element to start searching.

    Returns:
        RelativeBy: Use this object to create filters within a `find_elements` call.

    Raises:
        WebDriverException: If `tag_name` is None.

    Note:
        This method is deprecated and may be removed in future versions.
        Please use `locate_with` instead.
    """
    ...

def locate_with(by: ByType, using: str) -> RelativeBy:
    """Start searching for relative objects your search criteria with By.

    Args:
        by: The method to find the element.
        using: The value from `By` passed in.

    Returns:
        RelativeBy: Use this object to create filters within a `find_elements` call.

    Example:
        >>> lowest = driver.find_element(By.ID, "below")
        >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").above(lowest))
    """
    ...

class RelativeBy:
    """Find elements based on their relative location from a root element.

    It is recommended that you use the helper function to create instances.

    Example:
    --------
    >>> lowest = driver.find_element(By.ID, "below")
    >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").above(lowest))
    >>> ids = [el.get_attribute("id") for el in elements]
    >>> assert "above" in ids
    >>> assert "mid" in ids
    """

    LocatorType = dict[ByType, str]
    def __init__(self, root: dict[ByType, str] | None = ..., filters: list | None = ...) -> None:
        """Create a RelativeBy object (prefer using `locate_with` instead).

        Args:
            root: A dict with `By` enum as the key and the search query as the value
            filters: A list of the filters that will be searched. If none are passed
                in please use the fluent API on the object to create the filters
        """
        ...

    @overload
    def above(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def above(self, element_or_locator: None = ...) -> NoReturn: ...
    def above(self, element_or_locator: WebElement | LocatorType | None = ...) -> RelativeBy:
        """Add a filter to look for elements above.

        Args:
            element_or_locator: Element to look above

        Returns:
            RelativeBy

        Raises:
            WebDriverException: If `element_or_locator` is None.

        Example:
        --------
        >>> lowest = driver.find_element(By.ID, "below")
        >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").above(lowest))
        """
        ...

    @overload
    def below(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def below(self, element_or_locator: None = ...) -> NoReturn: ...
    def below(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements below.

        Args:
            element_or_locator: Element to look below

        Returns:
            RelativeBy

        Raises:
            WebDriverException: If `element_or_locator` is None.

        Example:
            >>> highest = driver.find_element(By.ID, "high")
            >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").below(highest))
        """
        ...

    @overload
    def to_left_of(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def to_left_of(self, element_or_locator: None = ...) -> NoReturn: ...
    def to_left_of(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements to the left of.

        Args:
            element_or_locator: Element to look to the left of

        Returns:
            RelativeBy

        Raises:
            WebDriverException: If `element_or_locator` is None.

        Example:
            >>> right = driver.find_element(By.ID, "right")
            >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").to_left_of(right))
        """
        ...

    @overload
    def to_right_of(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def to_right_of(self, element_or_locator: None = ...) -> NoReturn: ...
    def to_right_of(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements right of.

        Args:
            element_or_locator: Element to look right of

        Returns:
            RelativeBy

        Raises:
            WebDriverException: If `element_or_locator` is None.

        Example:
            >>> left = driver.find_element(By.ID, "left")
            >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").to_right_of(left))
        """
        ...

    @overload
    def straight_above(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def straight_above(self, element_or_locator: None = ...) -> NoReturn: ...
    def straight_above(
        self, element_or_locator: WebElement | LocatorType | None = ...
    ) -> RelativeBy:
        """Add a filter to look for elements above.

        Args:
            element_or_locator: Element to look above
        """
        ...

    @overload
    def straight_below(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def straight_below(self, element_or_locator: None = ...) -> NoReturn: ...
    def straight_below(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements below.

        Args:
            element_or_locator: Element to look below
        """
        ...

    @overload
    def straight_left_of(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def straight_left_of(self, element_or_locator: None = ...) -> NoReturn: ...
    def straight_left_of(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements to the left of.

        Args:
            element_or_locator: Element to look to the left of
        """
        ...

    @overload
    def straight_right_of(self, element_or_locator: WebElement | LocatorType) -> RelativeBy: ...
    @overload
    def straight_right_of(self, element_or_locator: None = ...) -> NoReturn: ...
    def straight_right_of(self, element_or_locator: WebElement | dict | None = ...) -> RelativeBy:
        """Add a filter to look for elements right of.

        Args:
            element_or_locator: Element to look right of
        """
        ...

    @overload
    def near(
        self, element_or_locator: WebElement | LocatorType, distance: int = ...
    ) -> RelativeBy: ...
    @overload
    def near(self, element_or_locator: None = ..., distance: int = ...) -> NoReturn: ...
    def near(
        self, element_or_locator: WebElement | LocatorType | None = ..., distance: int = ...
    ) -> RelativeBy:
        """Add a filter to look for elements near.

        Args:
            element_or_locator: Element to look near by the element or within a distance
            distance: Distance in pixel

        Returns:
            RelativeBy

        Raises:
            WebDriverException: If `element_or_locator` is None
            WebDriverException: If `distance` is less than or equal to 0.

        Example:
            >>> near = driver.find_element(By.ID, "near")
            >>> elements = driver.find_elements(locate_with(By.CSS_SELECTOR, "p").near(near, 50))
        """
        ...

    def to_dict(self) -> dict:
        """Create a dict to be passed to the driver for element searching."""
        ...
