"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common.webdriver import LocalWebDriver
from selenium.webdriver.ie.options import Options
from selenium.webdriver.ie.service import Service

class WebDriver(LocalWebDriver):
    """Control the IEServerDriver and drive Internet Explorer."""
    def __init__(
        self, options: Options | None = ..., service: Service | None = ..., keep_alive: bool = ...
    ) -> None:
        """Creates a new instance of the Ie driver.

        Starts the service and then creates new instance of Ie driver.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure RemoteConnection to use HTTP keep-alive.
        """
        ...
