"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chromium.webdriver import ChromiumDriver

class WebDriver(ChromiumDriver):
    """Controls the ChromeDriver and allows you to drive the browser."""
    def __init__(
        self, options: Options | None = ..., service: Service | None = ..., keep_alive: bool = ...
    ) -> None:
        """Creates a new instance of the chrome driver.

        Starts the service and then creates new instance of chrome driver.

        Args:
            options: Instance of Options.
            service: Service object for handling the browser driver if you need to pass extra details.
            keep_alive: Whether to configure ChromeRemoteConnection to use HTTP keep-alive.
        """
        ...
