"""
This type stub file was generated by pyright.
"""

import ast
import sys
import types
import unittest
import warnings
from collections.abc import Callable, Iterable, Sequence
from contextlib import _GeneratorContextManager
from pathlib import Path
from re import Pattern
from typing import (
    Any,
    AnyStr,
    ClassVar,
    Final,
    Generic,
    NoReturn,
    ParamSpec,
    Self,
    SupportsIndex,
    TypeAlias,
    TypeVar,
    TypeVarTuple,
    overload,
    type_check_only,
)
from typing import (
    Literal as L,
)
from unittest.case import SkipTest

import numpy as np
from _typeshed import ConvertibleToFloat, GenericPath, StrOrBytesPath, StrPath
from numpy._typing import (
    ArrayLike,
    DTypeLike,
    NDArray,
    _ArrayLikeDT64_co,
    _ArrayLikeNumber_co,
    _ArrayLikeObject_co,
    _ArrayLikeTD64_co,
)

__all__ = [
    "HAS_LAPACK64",
    "HAS_REFCOUNT",
    "IS_EDITABLE",
    "IS_MUSL",
    "IS_PYPY",
    "IS_PYSTON",
    "IS_WASM",
    "NOGIL_BUILD",
    "IgnoreException",
    "KnownFailureException",
    "SkipTest",
    "assert_",
    "assert_allclose",
    "assert_almost_equal",
    "assert_approx_equal",
    "assert_array_almost_equal",
    "assert_array_almost_equal_nulp",
    "assert_array_compare",
    "assert_array_equal",
    "assert_array_less",
    "assert_array_max_ulp",
    "assert_equal",
    "assert_no_gc_cycles",
    "assert_no_warnings",
    "assert_raises",
    "assert_raises_regex",
    "assert_string_equal",
    "assert_warns",
    "break_cycles",
    "build_err_msg",
    "check_support_sve",
    "clear_and_catch_warnings",
    "decorate_methods",
    "jiffies",
    "measure",
    "memusage",
    "print_assert_equal",
    "run_threaded",
    "rundocs",
    "runstring",
    "suppress_warnings",
    "tempdir",
    "temppath",
    "verbose",
]
_T = TypeVar("_T")
_Ts = TypeVarTuple("_Ts")
_Tss = ParamSpec("_Tss")
_ET = TypeVar("_ET", bound=BaseException, default=BaseException)
_FT = TypeVar("_FT", bound=Callable[..., Any])
_W_co = TypeVar("_W_co", bound=_WarnLog | None, default=_WarnLog | None, covariant=True)
_T_or_bool = TypeVar("_T_or_bool", default=bool)
type _StrLike = str | bytes
type _RegexLike = _StrLike | Pattern[Any]
type _NumericArrayLike = _ArrayLikeNumber_co | _ArrayLikeObject_co
_ExceptionSpec: TypeAlias = type[_ET] | tuple[type[_ET], ...]
type _WarningSpec = type[Warning]
type _WarnLog = list[warnings.WarningMessage]
type _ToModules = Iterable[types.ModuleType]
type _ComparisonFunc = Callable[
    [NDArray[Any], NDArray[Any]],
    bool | np.bool | np.number | NDArray[np.bool | np.number | np.object_],
]

@type_check_only
class _clear_and_catch_warnings_with_records(clear_and_catch_warnings):
    def __enter__(self) -> list[warnings.WarningMessage]: ...

@type_check_only
class _clear_and_catch_warnings_without_records(clear_and_catch_warnings):
    def __enter__(self) -> None: ...

verbose: int = ...
NUMPY_ROOT: Final[Path] = ...
IS_INSTALLED: Final[bool] = ...
IS_EDITABLE: Final[bool] = ...
IS_MUSL: Final[bool] = ...
IS_PYPY: Final[bool] = ...
IS_PYSTON: Final[bool] = ...
IS_WASM: Final[bool] = ...
HAS_REFCOUNT: Final[bool] = ...
HAS_LAPACK64: Final[bool] = ...
NOGIL_BUILD: Final[bool] = ...

class KnownFailureException(Exception): ...
class IgnoreException(Exception): ...

class clear_and_catch_warnings(warnings.catch_warnings[_W_co], Generic[_W_co]):
    class_modules: ClassVar[tuple[types.ModuleType, ...]] = ...
    modules: Final[set[types.ModuleType]]
    @overload
    def __init__(
        self: clear_and_catch_warnings[_WarnLog], /, record: L[True], modules: _ToModules = ...
    ) -> None: ...
    @overload
    def __init__(
        self: clear_and_catch_warnings[None], /, record: L[False] = ..., modules: _ToModules = ...
    ) -> None: ...
    @overload
    def __init__(self, /, record: bool, modules: _ToModules = ...) -> None: ...

class suppress_warnings:
    log: Final[_WarnLog]
    def __init__(
        self, /, forwarding_rule: L["always", "module", "once", "location"] = ...
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        cls: type[BaseException] | None,
        exc: BaseException | None,
        tb: types.TracebackType | None,
        /,
    ) -> None: ...
    def __call__(self, /, func: _FT) -> _FT: ...
    def filter(
        self,
        /,
        category: type[Warning] = ...,
        message: str = ...,
        module: types.ModuleType | None = ...,
    ) -> None: ...
    def record(
        self,
        /,
        category: type[Warning] = ...,
        message: str = ...,
        module: types.ModuleType | None = ...,
    ) -> _WarnLog: ...

if sys.platform == "win32" or sys.platform == "cygwin":
    def memusage(processName: str = ..., instance: int = ...) -> int: ...

else:
    def memusage(_proc_pid_stat: StrOrBytesPath = ...) -> int | None: ...
    def memusage() -> NoReturn: ...

if sys.platform == "linux":
    def jiffies(
        _proc_pid_stat: StrOrBytesPath | None = ..., _load_time: list[float] | None = ...
    ) -> int: ...

else:
    def jiffies(_load_time: list[float] = ...) -> int: ...

def build_err_msg(
    arrays: Iterable[object],
    err_msg: object,
    header: str = ...,
    verbose: bool = ...,
    names: Sequence[str] = ...,
    precision: SupportsIndex | None = ...,
) -> str: ...
def print_assert_equal(test_string: str, actual: object, desired: object) -> None: ...
def assert_(val: object, msg: str | Callable[[], str] = ...) -> None: ...
def assert_equal(
    actual: object,
    desired: object,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
def assert_almost_equal(
    actual: _NumericArrayLike,
    desired: _NumericArrayLike,
    decimal: int = ...,
    err_msg: object = ...,
    verbose: bool = ...,
) -> None: ...
def assert_approx_equal(
    actual: ConvertibleToFloat,
    desired: ConvertibleToFloat,
    significant: int = ...,
    err_msg: object = ...,
    verbose: bool = ...,
) -> None: ...
def assert_array_compare(
    comparison: _ComparisonFunc,
    x: ArrayLike,
    y: ArrayLike,
    err_msg: object = ...,
    verbose: bool = ...,
    header: str = ...,
    precision: SupportsIndex = ...,
    equal_nan: bool = ...,
    equal_inf: bool = ...,
    *,
    strict: bool = ...,
    names: tuple[str, str] = ...,
) -> None: ...
def assert_array_equal(
    actual: object,
    desired: object,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
def assert_array_almost_equal(
    actual: _NumericArrayLike,
    desired: _NumericArrayLike,
    decimal: float = ...,
    err_msg: object = ...,
    verbose: bool = ...,
) -> None: ...
@overload
def assert_array_less(
    x: _ArrayLikeDT64_co,
    y: _ArrayLikeDT64_co,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
@overload
def assert_array_less(
    x: _ArrayLikeTD64_co,
    y: _ArrayLikeTD64_co,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
@overload
def assert_array_less(
    x: _NumericArrayLike,
    y: _NumericArrayLike,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
def assert_string_equal(actual: str, desired: str) -> None: ...
@overload
def assert_raises(
    exception_class: _ExceptionSpec[_ET], /, *, msg: str | None = ...
) -> unittest.case._AssertRaisesContext[_ET]: ...
@overload
def assert_raises(
    exception_class: _ExceptionSpec,
    callable: Callable[_Tss, Any],
    /,
    *args: _Tss.args,
    **kwargs: _Tss.kwargs,
) -> None: ...
@overload
def assert_raises_regex(
    exception_class: _ExceptionSpec[_ET], expected_regexp: _RegexLike, *, msg: str | None = ...
) -> unittest.case._AssertRaisesContext[_ET]: ...
@overload
def assert_raises_regex(
    exception_class: _ExceptionSpec,
    expected_regexp: _RegexLike,
    callable: Callable[_Tss, Any],
    *args: _Tss.args,
    **kwargs: _Tss.kwargs,
) -> None: ...
@overload
def assert_allclose(
    actual: _ArrayLikeTD64_co,
    desired: _ArrayLikeTD64_co,
    rtol: float = ...,
    atol: float = ...,
    equal_nan: bool = ...,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
@overload
def assert_allclose(
    actual: _NumericArrayLike,
    desired: _NumericArrayLike,
    rtol: float = ...,
    atol: float = ...,
    equal_nan: bool = ...,
    err_msg: object = ...,
    verbose: bool = ...,
    *,
    strict: bool = ...,
) -> None: ...
def assert_array_almost_equal_nulp(
    x: _ArrayLikeNumber_co, y: _ArrayLikeNumber_co, nulp: float = ...
) -> None: ...
def assert_array_max_ulp(
    a: _ArrayLikeNumber_co,
    b: _ArrayLikeNumber_co,
    maxulp: float = ...,
    dtype: DTypeLike | None = ...,
) -> NDArray[Any]: ...
@overload
def assert_warns(warning_class: _WarningSpec) -> _GeneratorContextManager[None]: ...
@overload
def assert_warns(
    warning_class: _WarningSpec, func: Callable[_Tss, _T], *args: _Tss.args, **kwargs: _Tss.kwargs
) -> _T: ...
@overload
def assert_no_warnings() -> _GeneratorContextManager[None]: ...
@overload
def assert_no_warnings(
    func: Callable[_Tss, _T], /, *args: _Tss.args, **kwargs: _Tss.kwargs
) -> _T: ...
@overload
def assert_no_gc_cycles() -> _GeneratorContextManager[None]: ...
@overload
def assert_no_gc_cycles(
    func: Callable[_Tss, Any], /, *args: _Tss.args, **kwargs: _Tss.kwargs
) -> None: ...
@overload
def tempdir(
    suffix: None = ..., prefix: None = ..., dir: None = ...
) -> _GeneratorContextManager[str]: ...
@overload
def tempdir(
    suffix: AnyStr | None = ..., prefix: AnyStr | None = ..., *, dir: GenericPath[AnyStr]
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def tempdir(
    suffix: AnyStr | None = ..., *, prefix: AnyStr, dir: GenericPath[AnyStr] | None = ...
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def tempdir(
    suffix: AnyStr, prefix: AnyStr | None = ..., dir: GenericPath[AnyStr] | None = ...
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def temppath(
    suffix: None = ..., prefix: None = ..., dir: None = ..., text: bool = ...
) -> _GeneratorContextManager[str]: ...
@overload
def temppath(
    suffix: AnyStr | None, prefix: AnyStr | None, dir: GenericPath[AnyStr], text: bool = ...
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def temppath(
    suffix: AnyStr | None = ...,
    prefix: AnyStr | None = ...,
    *,
    dir: GenericPath[AnyStr],
    text: bool = ...,
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def temppath(
    suffix: AnyStr | None, prefix: AnyStr, dir: GenericPath[AnyStr] | None = ..., text: bool = ...
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def temppath(
    suffix: AnyStr | None = ...,
    *,
    prefix: AnyStr,
    dir: GenericPath[AnyStr] | None = ...,
    text: bool = ...,
) -> _GeneratorContextManager[AnyStr]: ...
@overload
def temppath(
    suffix: AnyStr,
    prefix: AnyStr | None = ...,
    dir: GenericPath[AnyStr] | None = ...,
    text: bool = ...,
) -> _GeneratorContextManager[AnyStr]: ...
def check_support_sve(__cache: list[_T_or_bool] = ...) -> _T_or_bool: ...
def decorate_methods(
    cls: type, decorator: Callable[[Callable[..., Any]], Any], testmatch: _RegexLike | None = ...
) -> None: ...
@overload
def run_threaded(
    func: Callable[[], None],
    max_workers: int = ...,
    pass_count: bool = ...,
    pass_barrier: bool = ...,
    outer_iterations: int = ...,
    prepare_args: None = ...,
) -> None: ...
@overload
def run_threaded(
    func: Callable[[*_Ts], None],
    max_workers: int,
    pass_count: bool,
    pass_barrier: bool,
    outer_iterations: int,
    prepare_args: tuple[*_Ts],
) -> None: ...
@overload
def run_threaded(
    func: Callable[[*_Ts], None],
    max_workers: int = ...,
    pass_count: bool = ...,
    pass_barrier: bool = ...,
    outer_iterations: int = ...,
    *,
    prepare_args: tuple[*_Ts],
) -> None: ...
def runstring(astr: _StrLike | types.CodeType, dict: dict[str, Any] | None) -> Any: ...
def rundocs(filename: StrPath | None = ..., raise_on_error: bool = ...) -> None: ...
def measure(code_str: _StrLike | ast.AST, times: int = ..., label: str | None = ...) -> float: ...
def break_cycles() -> None: ...
