"""
This type stub file was generated by pyright.
"""

from pandas._typing import NDFrameT
from pandas.core.window.rolling import BaseWindowGroupby, RollingAndExpandingMixin

class Expanding(RollingAndExpandingMixin[NDFrameT]): ...
class ExpandingGroupby(BaseWindowGroupby[NDFrameT], Expanding[NDFrameT]): ...
