"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any

class LogEntryAdded:
    event_class = ...
    @classmethod
    def from_json(cls, json: dict[str, Any]) -> ConsoleLogEntry | JavaScriptLogEntry | None: ...

@dataclass
class ConsoleLogEntry:
    level: str
    text: str
    timestamp: str
    method: str
    args: list[dict[str, Any]]
    type_: str
    @classmethod
    def from_json(cls, json: dict[str, Any]) -> ConsoleLogEntry: ...

@dataclass
class JavaScriptLogEntry:
    level: str
    text: str
    timestamp: str
    stacktrace: dict[str, Any]
    type_: str
    @classmethod
    def from_json(cls, json: dict[str, Any]) -> JavaScriptLogEntry: ...

class LogLevel:
    """Represents log level."""

    DEBUG = ...
    INFO = ...
    WARN = ...
    ERROR = ...
