name: Python Releases
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/typings'
env:
  PYTHON_VERSION: '3.12'
jobs:
  versions:
    name: Update Releases / Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft Release
        id: release
        # Drafts your next Release notes as Pull Requests are merged into "main"
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-autolabeler: true
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/*/poetry.lock') }}
      - name: Update project versions
        id: version
        run: |
          echo "Next Version: ${{ steps.release.outputs.tag_name }}"
          poetry version ${{ steps.release.outputs.tag_name	}}
          poetry update marktplaats_scraper
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump project version to ${{ steps.release.outputs.tag_name }}
          file_pattern: "pyproject.toml poetry.lock"
